### PR TITLE
Implement bikesharing-bz Data Collector

### PR DESCRIPTION
**Pull request by edp-progetti**
In this pull request there is the implementation of the data collector, with almost all test cases. Documentation must be finished but should be enough to check in development environment if data is imported correctly in the Open data Hub.

### CODE REVIEW

**Comment by edp-progetti** [comment]
It is necessary to inject the variable "app.auth.token" in file application.properties with the string representing the authorization TOKEN to access services provided by Ecospazio.

**Comment by bertolla** [comment]
> It is necessary to inject the variable "app.auth.token" in file application.properties with the string representing the authorization TOKEN to access services provided by Ecospazio.
OK we'll do that, but the ci is currently not passing because of a unit test which fails.
Can you @edp-progetti take a look?
`[ERROR]   MeasurementProcessorParametersTest.get_parameters_of_existing_station_and_res_val_id:27 expected:<-1075.7313> but was:<1277.0>
`

**Comment by edp-progetti** [comment]
Hi @bertolla, that test class sounded strange to me, I looked into the error and saw that the class MeasurementProcessorParametersTest is inside "environment-a22" data collector and is not part of my pull request. 
Tell me if now the simplest thing to do is that I change also that test class inside my pull request or if it is better that the change is done by the author.

**Comment by bertolla** [comment]
You are right wee need a better approach for CI in bdp-commons. This way does not work anymore.

**Comment by bertolla** [comment]
@rcavaliere Please provide me with the 'auth token' of ecospazio through encryptet mail or our cloud service.

**Comment by rcavaliere** [comment]
Done, please let me you know if you received it.

**Pull request merged**
