### PR TITLE
A22 events data collector

### PR DESCRIPTION
**Pull request by noctho**

### CODE REVIEW

**Comment by Piiit** [comment]
@noctho Thanks for the PR, we will try to have a look in two weeks time... in the meantime please consider that we always want to have all comments and variable names in English. Would it be possible that you update this PR accordingly?

**Review by Piiit — CHANGES_REQUESTED** [review]
See last comment in "Conversation"

**Comment by noctho** [comment]
Ok, I'll check the comments/names within the next week and then update the PR afterwards.

**Comment by noctho** [comment]
In the MainA22Events class I've found some variables and constants in Italian. But in every case they or parts of them correspond to the specified names of the metadata or the column names of the csv file.

I've created a constant for each metadata with the following format: `STATION_ METADATA_<metadata-name>`.

In two other cases I've used the column name of the file `SottotipiEventi.csv`, which is provided by A22, as the variable name.

So in order to have a 1 to 1 mapping between the variable or constant names and their value, I have taken the value as part of the name.

Apart from that, I only found one log that is partly in Italian and I will update it.

Since @chris-mair is the author of the classes A22Event, A22BrennerLECEvent, A22EventConnector and Main, I would like to ask him for a comment regarding the non-English variable names and comments.

**Comment by chris-mair** [comment]
@Piiit 

hi, I've opted out from mail by github, if you need a comment from me, please mail me.

Regarding non-English variable names and comments please consider the fact that this is a mapping class that maps
entitities right out of a JSON provided by A22 with Italian field-names. To keep things as clear as possibile I thought it
was best to just use their (i.e. A22's) nomenclature.

The comments are copied straight out of the A22 specification document.

I would suggest to leave the names as they are.

-- Chris

**Comment by Piiit** [comment]
@noctho @chris-mair OK, I understand... it this case it makes sense...

**Pull request merged**
